### ISSUE TITLE
是否考虑增加登录验证？

### ISSUE THREAD

**Issue by frankwuzp** [gps949/LittleLedger#2]
感谢大佬的开源！已 docker 部署
是否考虑增加登录验证的界面？以免被人看到余额，导致尴尬的境地

**Comment by gps949** [comment]
实际上web app页面上不会直接显示任何账户余额、动账交易数据信息，增加验证会增加使用复杂性，不建议添加。
但还是作为可选设置添加上了，使用Docker的话更新到最新镜像或者v0.3版本，使用源码的话更新到最新，按照更新后的README操作。
