### ISSUE TITLE
docker运行命令有处错误

### ISSUE THREAD

**Issue by Jiangnanmisty** [gps949/LittleLedger#6]
`docker run --privile**d**ged=true -d --restart=always -e LL_USER=<你的用户名> -e LL_PWD=<你的口令> -p <本地服务端口>:3456 -v <持久存放账本本地路径>:/home/littleledger/ledgers gps949/littleledger:latest`
应该删除**d**

**Comment by gps949** [comment]
fixed by 99058281be97f527f6d0e5afeafbea81870c4452

**Comment by Jiangnanmisty** [comment]
priviledged这个单词拼写错误了。。。 应该是privileged

**Comment by gps949** [comment]
> priviledged这个单词拼写错误了。。。 应该是privileged

哈哈，不好意思，没注意看你给出的里面的星号，光看到下面了，还以为说的是-d参数呢
